MAX_NAME_LENGTH = 256

MAX_TAG_NAME_LENGTH = 32
MAX_SLUG_LENGTH = 32
MAX_UNIT_LENGTH = 20

MAX_USER_NAME_LENGTH = 150
MAX_EMAIL_LENGTH = 254

MIN_AMOUNT_INGREDIENTS = 1
MIN_COOKING_TIME = 1

POSTS_PER_PAGE = 10
INGREDIENTS_PER_PAGE = 20

SHORT_LINK_URL_PATH = "s"

MIN_LENGTH_FOR_SHORT_URL = 3
SALT = "mysecret"

PDF_FILENAME = "spisok_pokupok.pdf"

FONT_SIZE_HEADER = 16
FONT_SIZE_INGREDIENTS = 10
INDENT_REGULAR = 40
