MAX_NAME_LENGTH = 256
MAX_LENGTH_SLUG = 50

MAX_USER_NAME_LENGTH = 150
MAX_EMAIL_LENGTH = 254
MAX_ROLE_LENGTH = 20

MIN_AMOUNT_INGREDIENTS = 1

POST_PER_PAGE = 10

COMMENT_LENGHT = 15

ADMIN_EMAIL = "noreply@yamdb.com"
